services:

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: refmex_db
      CORS_ORIGINS: "*"
      ENVIRONMENT: production
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  mongo_data:
